str1 = 'GAGTGCACTACGCTGCTTCACGAGGCTGGGATAGACACTCCATCTACTTTGCACTCACATATTTCAGAAGGCGAGAGCAAATTATCGATTCCCGCAAGTCCGGCAGCTGAAAGTCTATTGGAGTGTTTCTGACGTCTGCGCAAGACCCCGGTATCCATGATACAACAAACGCAATGATCGCACGGTGAGGGGCTTGGCAGGTGCGGCAAACGAACCGGGGGGAGACTCAACGTATCTGTCAGGGGAGCAGTCGTGTATAGCTGGTCAAGCTCTTCGTAATTGTTATACCTGGCGGAGCGTCAATCCAGTCTGTAATATGCCAAGCCGCTGAGGTCGCGACCCTCGACCCGCGTAAAGGTAAGGGTACGGCGCCTGACTGGTCTGATATATGTACGGGCTGTGTGTAGTTACAATCAGAGGCACGTCCGAACCTGGGGTATATTCTTAATGCGTGGTCATACAGCCCGCCAAGGACTATAACATAGCCGGGTCCGTGAAAATATTGGATCTATCTTTAATGGTTACGCAAAACTGCTGCACCCGTTGCACTTGAATAATATACTCGGCTCACCGATTTAACCATGGGCGCTGGCAATATTTGTACAATGTGAGTCGCCAGGATAATACATAACTACTTGATAGAACAAGCCATGTCTGGACCCGTTGCCTACCTAGGATTCAATGAGATTCTGCTGTCTGCACCCCTAGACCACAAATCAGGGTTACACATGTCTCGTCCAAGACATGCAGATCTCGTTCACGATTAACGTCCTGTTCAAACATAACCGCTCGGCCTATCTTATAGTGTAGGGAAAAATACTTGCGGCCT'
cnt = {'A':0, 'C':0, 'G':0, 'T':0}
for c in str1:
    cnt[c] += 1;

print(str(cnt['A']) + ' ' + str(cnt['C']) + ' ' + str(cnt['G']) + ' ' + str(cnt['T']))

