string1 = "GATGGGGAGCGTTAAATGAAAGTAGGCAATTCATGTTCATGCGGGACTTTTACTGAGAGGATAGCGAACTCCTCGCCGGCAGCGACGTTAGTAATACTCTCATGGGCATAGCTGGCCGATGAGCGGAATCGAATGTTCATGAGTTCGTCAGGTTCAAGGGAGGGTGCTATGTGTCCAGGACACAGAATCCCTTCTCGATTAAGGAATTGCTGTCTATGTACCCCCGGGTGTACACAGGAGAGTTAGCTACTGATATTATCTGTTGTGGGATGAGGATCAAACCGGAAAGATGACCCAACGTCACCCGGATCTGGATAGATGTAGCGCCCCGGGTTGGGCTATAATTCCGTGGGCATCCGTTTTCCCGATGAGCGCTAGGCTGGGGTCGTCCACTCTATTCCACCTGTCTTTATTATAGAACTCTAATCCTAAGGGTTCTGAAATGATGAGCGAGTTGTGTCGTTATAAGGTGTGGATAGTTACTGTTAGCTAACCAAATCTATGCTTAGAAAATATGTTGGGCAAGCAGGCGCGCCCTTATATGATAGGTCGTCGCGAGTGTCAGATGCCCCTCCATACCAAATAAAATATTCTGTACGCGGGCACCCTATGCCGTATTGTCAGCGCACAATGTTTGCCTCCCCAATGCAGAGGACGGTGGAGCTCAATCCGGATTCAACCAATCCTATACTACACTACATCTTATTACCTCGTGGGTGTTTGGGTGAGGGAGCGGTCTAGCCGACCGAGAAGGATCGTGATCGGTGGGCTTTCTAGAGTGCAACGGCTTGGTCGTGTTCCCACTTATTGGCTCCTATTCCCGCTTGATGCCGACGCATTGGACCTACGACATAATC"
string2 = "CCCCGGGCAGATTTGCCGAATTATCTGCCAGGCTTATATACAGGGATTGGGTTCCAATGAAGAACGCTAGACTTCCCACTATGGTTATGACCTTCCATCCGCATACGACCTACAGTCACAAACTTTGTCCAAGTTGTTACCACGACAAGTGACTTCCAGACCGCAATGCCATGTATCTCAGCGCGAGAGATATGAGCACTCATTGACTAGATTTCCCCATCTTCCGCCTAGTACGTCGACGGTATGAAGAAACGTCTAGTGTAAGGTCGAAACTATGAGCTCACACCCTGCATCACGTTATCTGGAGGCGATGAAGCACTTCTCGATGGGGCTTTCATAGTACGGGTGGATATGGCCATTTCATGCTCACATGTGTCTCCTCTCGCAACCATTCCGCAACAACTAGGCGGCGGGTTCGAGGTTAGATGTTCATGCCCACGAGGACGCTTCTATAGTACCTACTCGGGCAGTTGATCCCTGGCCGGAGCTACGGGATATTAGTACTACTTATCAAGATTATGCGGACGAGACGGACCGGTGAGGCGAGCCCAATCTTCTTCGCAGGCTCAGACTAGCGAGAATATTGGAATCGTGCCGCCTCAACTCGCTACGGTCTTAGCAAACGGCCCGAAGAGCGTAAGCACCACTCTGTAACATCCGCCCAATGTTTCGTTTTGATCGACGTTGAGTGTGCGCGTCTGCGGCACGATGACTTTACCCGGACACACAGAAGTCGTAATTGCTGACACCACAGTGTCATCACACCGTGCCTCGGAGGATAAGACTCCCATTACGTAGGAGCATAACGAGGGCTATGCTTTTGTCTCATTATGGCGCAACCAACTTGGGCCCGATGCCACGGACCGGGGCCCCGTGACATCACTGAAAAACTTGTTTGCAGGGGTGGGACTTAATTCGTCTGCCCGCACATAGTCGTGTTACTGGGTGTCCGCATCG"

subseq = [[0]*(len(string1)+1) for i in range(len(string2)+1)]
subseq2 = [['']*(len(string1)+1) for i in range(len(string2)+1)]

for i in range(1, len(string2)+1):
    for j in range(1, len(string1)+1):
        if string2[i-1] == string1[j-1]:
            subseq[i][j] = 1 + subseq[i-1][j-1]
            subseq2[i][j] = subseq2[i-1][j-1] + string2[i-1]
        else:
            if subseq[i-1][j] > subseq[i][j-1]:
                subseq[i][j] = subseq[i-1][j]
                subseq2[i][j] = subseq2[i - 1][j]
            else:
                subseq[i][j] = subseq[i][j-1]
                subseq2[i][j] = subseq2[i][j-1]

print(subseq2[len(string2)][len(string1)])


